check_emailed_photos:
  # using rufus format: https://github.com/jmettraux/rufus-scheduler
  every: 1m
  class: "EmailChecker"
  queue: :email_checker
  args:
  description: "This job checks for recent emailed photos"