# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11cc698a3af775d05b96a9300b7986b3682355410a173f2eb98c0ff46091715cf793d1c3eab65eea02a041e875a81770f3b1beace3d7dab93ad2b2587fcbb497

test:
  secret_key_base: 11cc698a3af775d05b96a9300b7986b3682355410a173f2eb98c0ff46091715cf793d1c3eab65eea02a041e875a81770f3b1beace3d7dab93ad2b2587fcbb497

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
